version: '3'
services:
  nest:
    build:
      context: .
      target: development
    container_name: nest
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    command: npm run start:debug
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
