version: '3'
services:
  nest:
    image: truongtrongtin/learn-nestjs:latest
    container_name: nest
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443

  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - certbot-etc:/etc/letsencrypt
  #     - certbot-var:/var/lib/letsencrypt
  #     - web-root:/var/www/html
  #   depends_on:
  #     - nginx
  #   command: certonly \
  #     --webroot \
  #     --webroot-path=/var/www/html \
  #     --email sammy@example.com \
  #     --agree-tos \
  #     --no-eff-email \
  #     --staging \
  #     -d example.com \
  #     -d www.example.com

volumes:
  postgres:
